# @format

BOT:
  OWNERS: [""]
  ADMINS: [""]

LINKS:
  SUPPORT: "https://discord.gg/"
  MONGO_URI: "mongodb+srv://:@.mzc7ria.mongodb.net/"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "98f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: ""
  TOKEN: ""

FUEGO:
  PREFIX: "1"
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: ""


WEBHOOKS:
  ERROR: ""
  STATIC: ""
  PLAYER: ""
  SERVER: ""
  COMMAND: ""
